# Generated by Django 4.2.16 on 2024-11-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 15, 0, 50, 26634)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 15, 0, 50, 26634)),
        ),
    ]
