# Generated by Django 4.2.16 on 2024-11-08 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('vehiculo.view', 'Puede ver los vehiculos'), ('visualizar_catalogo', 'Puede ver lista de vehiculos'), ('can_add_vehiculo_model', 'Can add vehiculo model'), ('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')], 'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga')], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 16, 41, 8, 599067)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 16, 41, 8, 599067)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], default='Ford', max_length=20),
        ),
    ]
