# Generated by Django 4.2.16 on 2024-11-09 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_vehiculo_options_alter_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 21, 24, 11, 436207)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 21, 24, 11, 436207)),
        ),
    ]
